// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../app/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../../../app/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/moderation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/moderation">> = Specific
  const handler = {} as typeof import("../../../../app/moderation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity">> = Specific
  const handler = {} as typeof import("../../../../app/api/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/announcement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcement">> = Specific
  const handler = {} as typeof import("../../../../app/api/announcement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/bot-bio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot-bio">> = Specific
  const handler = {} as typeof import("../../../../app/api/bot-bio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/bot-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot-profile">> = Specific
  const handler = {} as typeof import("../../../../app/api/bot-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/bot-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bot-status">> = Specific
  const handler = {} as typeof import("../../../../app/api/bot-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/channels">> = Specific
  const handler = {} as typeof import("../../../../app/api/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/guilds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guilds">> = Specific
  const handler = {} as typeof import("../../../../app/api/guilds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login">> = Specific
  const handler = {} as typeof import("../../../../app/api/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logout">> = Specific
  const handler = {} as typeof import("../../../../app/api/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/moderation/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moderation/actions">> = Specific
  const handler = {} as typeof import("../../../../app/api/moderation/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/moderation/warnings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moderation/warnings">> = Specific
  const handler = {} as typeof import("../../../../app/api/moderation/warnings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../app/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats">> = Specific
  const handler = {} as typeof import("../../../../app/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
